### ISSUE TITLE
predict_proba method does not work for ExpertRuleClassifier 

### ISSUE THREAD

**Issue by cjw199** [adaa-polsl/RuleKit-python#10]
The ExpertRuleClassifier has the predict_proba method, but does not seem to have the label_unique_values attribute that the method requires.  Calling this method returns the error message:
AttributeError: 'ExpertRuleClassifier' object has no attribute 'label_unique_values'

A minimal example is to follow the expert rules classifier tutorial and after fitting the model, call
`clf.predict_proba(x)`

**Comment by cezary986** [comment]
Thank you very much for reporting this bug! It has been successfully fixed in the latest version (v1.7.1).
