### ISSUE TITLE
Missing parameters user_induction_equation/user_pruning_equation/user_voting_equation

### ISSUE THREAD

**Issue by Margaid** [adaa-polsl/RuleKit-python#24]
In the RuleKit documentation, there are parameters named user_induction_equation/user_pruning_equation/user_voting_equation. However, I couldn't find their equivalents in the Python wrapper documentation. Only under the pruning_measure parameter, it is mentioned that it's possible to define a measure using a string, but this option doesn't work - only measures listed in Measures (enum) are allowed. I've attempted to do this for a classification and regression like this:

`clf=RuleClassifier(
    pruning_measure='2*p/n'
)`

and this code throws a validation error:
```
1 validation error for ClassificationParams
pruning_measure
  Input should be 'Accuracy', 'BinaryEntropy', 'C1', 'C2', 'CFoil', 'CN2Significnce', 'Correlation', 'Coverage', 'FBayesianConfirmation', 'FMeasure', 'FullCoverage', 'GeoRSS', 'GMeasure', 'InformationGain', 'JMeasure', 'Kappa', 'Klosgen', 'Laplace', 'Lift', 'LogicalSufficiency', 'LogRank', 'MEstimate', 'MutualSupport', 'Novelty', 'OddsRatio', 'OneWaySupport', 'PawlakDependencyFactor', 'Precision', 'Q2', 'RelativeRisk', 'Ripper', 'RSS', 'RuleInterest', 'SBayesian', 'Sensitivity', 'Specificity', 'TwoWaySupport', 'WeightedLaplace', 'WeightedRelativeAccuracy' or 'YAILS' [type=enum, input_value='2*p/n', input_type=str]
```

**Comment by cezary986** [comment]
This was in fact a missing functionality which will be added in the next release. The pull request for this functionality is here: https://github.com/adaa-polsl/RuleKit-python/pull/33.  It will allow user to easily define custom quality measures using python functions.
